steps:

  - name: python:3.10
    entrypoint: python
    args: ['-m', 'pip', 'install', '-r', 'tests/requirements.txt', '--user']

  - name: python:3.10
    entrypoint: 'python'
    args: ['-m', 'pytest', '-v']

options:
  logging: CLOUD_LOGGING_ONLY
