steps:
- name: python:3.10
  entrypoint: bash
  args:
  - -eux
  - |
    # install everything you need
    python -m pip install --upgrade pip keyrings.google-artifactregistry-auth build twine 

    # build your wheel/sdist
    python -m build

    # upload using the keyring plugin (no user/pass needed)
    python -m twine upload \
      --repository-url https://europe-west3-python.pkg.dev/one-data-project/daailyapis-python-client/ \
      --skip-existing \
      dist/*

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
