# FIFI CREDENTIALS ENV KEYS
FIFI_AUTH_USERNAME_ENV = "FIFI_AUTH_USERNAME"
FIFI_AUTH_PASSWORD_ENV = "FIFI_AUTH_PASSWORD"

# ENV KEY ERROR MESSAGE
MISSING_ENV_FIFI_CREDENTIALS_MESSAGE = (
    "Fifi credentials should be set via the environment."
)
