name: Test Suite Daaily Package
on:
  push:
    branches:
       - '**'

jobs:
  linting-and-formatting:
    name: Linting / Formatting
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
            cache: 'pip'
        - run: pip install -r tests/requirements.txt
        - name: Lint with Ruff
          run: ruff check -n --config=pyproject.toml .
        - name: Check code format with Black
          run: python -m black --check --diff --config=pyproject.toml .