name: Test Suite Daaily Package
on:
  push:
    branches:
       - '**'

# name: Ruff
# on: [ push, pull_request ]
jobs:
  ruff-linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
# jobs:
  # test-suite:
  #   name: Linting / Formatting
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v3
  #       - uses: actions/setup-python@v4
  #         with:
  #           python-version: '3.12'
  #           cache: 'pip'
  #       - run: pip install -r tests/requirements.txt
  #       - name: Lint with Ruff
  #         run: ruff check -n --config=pyproject.toml .
  #       - name: Check code format with Black
  #         run: python -m black --check --diff --config=pyproject.toml .