name: Test Suite Daaily Package
on:
  push:
    branches:
       - '**'

jobs:
  ruff-linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1